version: 1.1.0-{build}

branches:
  only:
    - master

pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2017

install:
  - ps: Install-Product node 8.6.0 x64

environment:
  SlnFile: ../Source/Reporting/Reporting.sln
  WebBinFolder: ../Source/Reporting/Web/bin
  AngularFolder: ../Source/Reporting/Web.Angular

only_commits:
  files:
    - Source/Reporting/

build_script:
- ps: ./Build/build.ps1

test: off
